### ISSUE TITLE
Rstp stream 

### ISSUE THREAD

**Issue by mfoglio** [jishnujayakumar/MV-Tractus#26]
Can I use this tool with an rstp stream ?

**Comment by jishnujayakumar** [comment]
Hi @mfoglio,

Sorry for the delayed reply. As I mentioned the [README](https://github.com/jishnujayakumar/MV-Tractus#note-due-to-the-lack-of-time-i-am-not-able-to-maintain-this-project-i-would-like-to-request-the-users-and-contributors-to-help-each-other-in-all-possible-ways-by-joining-slack), I am not able to maintain the codebase as well as reply on-time due to the lack of time. If you meant RTSP stream, then I believe yes. I have not tried personally though.
