### ISSUE TITLE
Can FFMPEG pipe to MV-Tractus for live webcam feed to be used as motion detection?

### ISSUE THREAD

**Issue by rajhlinux** [jishnujayakumar/MV-Tractus#30]
Hello,

I'm curious if I can I use MV-Tractus as motion detection for webcams.
Basically would like to record using FFMPEG and also at the same time take snaphots when motion is detected with the help of MV-Tractus. Is it possible to do so?

Thanks.

**Comment by jishnujayakumar** [comment]
@rajhlinux,

Sorry for the delayed reply. As I mentioned the [README](https://github.com/jishnujayakumar/MV-Tractus#note-due-to-the-lack-of-time-i-am-not-able-to-maintain-this-project-i-would-like-to-request-the-users-and-contributors-to-help-each-other-in-all-possible-ways-by-joining-slack), I am not able to maintain the codebase as well reply on-time due to the lack of time. Since MV-Tractus is a wrapper written on top of FFMPEG with the sole purpose of extracting motion vectors, I am afraid that it won't help in your use-case.
